name: fitness-io

on:
    push:
        branches:
            - master

jobs:
    install_dependencies:
        runs-on: Ubuntu-24.04

        steps:
        - name: Checkout code
          uses: actions/setup-node@v3

        - name: Install dependencies
          run: |
           yarn install

    docker_push:
        runs-on: Ubuntu-24.04
        
        steps:
        - name: Build Docker image
          working-directory: ./
          run: |
            docker build -t allanbinga/fitness-io:v1.0.0 .
        
        - name: Log in to DockerHub
          run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Push image to DockerHub.
          working-directory: ./
          run: |
            docker push allanbinga/fitness-io:v1.0.0    
    
    